### ISSUE TITLE
Dark theme support

### ISSUE THREAD

**Issue by ohkimur** [decameronn/fuzzy-theme#1]
The current version of the theme has potential. I would very much like to see a dark version of it.

**NOTE**: A more minimalist logo would help people in creating a better relationship with the theme in the marketplace.

**Comment by ohkimur** [comment]
Also, I think the contrast of some colors isn't that great for the eyes. For example, the yellow for rainbow brackets doesn't read well on the theme light background. Maybe this helps in improving the theme, so more people could use it every day.

**Comment by weightofcode** [comment]
> The current version of the theme has potential. I would very much like to see a dark version of it.
> 
> **NOTE**: A more minimalist logo would help people in creating a better relationship with the theme in the marketplace.

Thank you for the feedback. 
1. A dark version of the theme is planned.
2. Indeed, the logo can be (greatly) improved and there will probably be at least one newer iteration of it in the future

**Comment by weightofcode** [comment]
> Also, I think the contrast of some colors isn't that great for the eyes. For example, the yellow for rainbow brackets doesn't read well on the theme light background. Maybe this helps in improving the theme, so more people could use it every day.

I will check this on my end and get back to you with an update. Thank you!

**Comment by weightofcode** [comment]
> > Also, I think the contrast of some colors isn't that great for the eyes. For example, the yellow for rainbow brackets doesn't read well on the theme light background. Maybe this helps in improving the theme, so more people could use it every day.
> 
> I will check this on my end and get back to you with an update. Thank you!

This is proving to be quite an endeavor!

**Comment by ohkimur** [comment]
> > > Also, I think the contrast of some colors isn't that great for the eyes. For example, the yellow for rainbow brackets doesn't read well on the theme light background. Maybe this helps in improving the theme, so more people could use it every day.
> > 
> > 
> > I will check this on my end and get back to you with an update. Thank you!
> 
> This is proving to be quite an endeavor!

Maybe [this ](https://medium.com/outcrowd/top-secrets-of-contrast-in-design-8c8fc8dc463f) article helps a little bit.

**Comment by weightofcode** [comment]
> The current version of the theme has potential. I would very much like to see a dark version of it.

The work on dark version has started. Stay tuned!

**Comment by weightofcode** [comment]
Later Edit: improvements for Light theme are underway (they were long overdue), therefore Dark version is postponed for now.

**Comment by weightofcode** [comment]
Light version rework finished. Progress on Dark Theme resumed.

**Comment by weightofcode** [comment]
FuZZy Dark Theme has been released.
Thank you for the suggestion! 😊
